// Auto-generated by backend/scripts/export_material_categories.py
export const MATERIAL_CATEGORIES = [
  "五金辅料",
  "劳保用品",
  "包装材料",
  "包装相关",
  "半成品件",
  "半成品料",
  "印染材料",
  "备货部件",
  "安装物料",
  "工具耗材",
  "成品批布",
  "成品配料",
  "成品配饰",
  "打印介质",
  "板材板料",
  "模块库存",
  "电子灯光",
  "画框线条",
  "白坯面料",
  "组合辅料",
  "装裱材料",
  "通用物料",
  "颜料涂料",
  "颜色介质"
] as const;
export type MaterialCategory = typeof MATERIAL_CATEGORIES[number];
